os: linux
dist: xenial
language: php

addons:
  chrome: stable
  firefox: latest
  apt:
    update: true
    packages:
      # Ubuntu 16+ does not install this dependency by default.
      - libgconf-2-4
      - chromium-chromedriver

services:
  - xvfb

# Downloaded browsers will be cached in selenium-assistant by
# web-push-testing-service. Caching will speed up build time.
cache:
  directories:
    - ~/.selenium-assistant
    - $COMPOSER_CACHE_DIR
    - $HOME/.composer/cache
    - node_modules
    - vendor

jobs:
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

env:
  global:
    - TRAVIS_NODE_VERSION="stable"

before_install:
  - composer config discard-changes true
  - nvm install node

install:
  - npm i -g "https://github.com/GoogleChromeLabs/web-push-testing-service.git#012508983fa5dd3d25d06f0b937f92c33fc71382"
  - composer install --prefer-source -n

script:
  - echo "Preparing unit tests skipped, will check locally" # web-push-testing-service start example -p 9012
  - echo "Unit tests skipped, will check locally" # composer test:unit
  - echo "Finishing unit tests skipped, will check locally" # web-push-testing-service stop example
  - composer test:typing
  - composer test:syntax
